$replacements = @{
    # ── DTO Properties ─────────────────────────────────────────────
    '\bTopicName\b'           = 'TenChuDe'
    '\bTopicIcon\b'           = 'BieuTuongChuDe'
    '\bStarsToUnlock\b'       = 'SaoDeMoKhoa'
    '\bParentID\b'            = 'MaChuDeCha'
    '\bSortOrder\b'           = 'ThuTuSapXep'
    '\bLevelID\b'             = 'MaMuc'
    '\bLevelName\b'           = 'TenMuc'
    '\bDifficultyLevel\b'     = 'DoKho'
    '\bQuestionCount\b'       = 'SoCauHoi'
    '\bWordID\b'              = 'MaTu'
    '\bEnglishWord\b'         = 'TiengAnh'
    '\bVietnameseMeaning\b'   = 'NghiaTiengViet'
    '\bPhonetic\b'            = 'PhienAm'
    '\bEmojiIcon\b'           = 'BieuTuong'
    '\bImagePath\b'           = 'DuongDanAnh'
    '\bImageID\b'             = 'MaAnh'
    '\bDifficulty\b'          = 'DoKho'
    '\bKeyword\b'             = 'TuKhoa'
    '\bImageFilter\b'         = 'BoDieuHoa'
    '\bRuleID\b'              = 'MaLuat'
    '\bLives\b'               = 'SoMang'
    '\bTimeLimit\b'           = 'GioiHanThoiGian'
    '\bBaseScore\b'           = 'DiemCoBan'
    '\bStreakBonus\b'         = 'ThuongChuoiDiem'
    '\bHintPenalty\b'         = 'PhatGoi'
    '\bStar1Threshold\b'      = 'NguongSao1'
    '\bStar2Threshold\b'      = 'NguongSao2'
    '\bStar3Threshold\b'      = 'NguongSao3'
    '\bGameMode\b'            = 'CheDoCHoi'
    '\bMaxLives\b'            = 'SoMangToiDa'
    '\bStreak\b'              = 'ChuoiDiem'
    '\bCorrectCount\b'        = 'SoCauDung'
    '\bTotalQuestions\b'      = 'TongCauHoi'
    '\bRemainingTimeMs\b'     = 'ThoiGianConLaiMs'
    '\bMaxTimeMs\b'           = 'ThoiGianToiDaMs'
    '\bTotalTimeSpentMs\b'    = 'TongThoiGianMs'
    '\bCurrentWordIndex\b'    = 'ViTriTuHienTai'
    '\bIsAnswered\b'          = 'DaTraLoi'
    '\bIsGameOver\b'          = 'KetThucGame'
    '\bIsWaitingForNext\b'    = 'DangChoTiep'
    '\bCurrentInput\b'        = 'NhapHienTai'
    '\bAvailableLetters\b'    = 'ChuCaiCoThe'
    '\bCorrectAnswer\b'       = 'DapAnDung'
    '\bCurrentQuestionText\b' = 'CauHoiHienTai'
    '\bLivesDisplay\b'        = 'HienThiMang'
    '\bHintUsedCount\b'       = 'SoLanGoiY'
    '\bRemainingSeconds\b'    = 'GiayConLai'
    '\bProgressPercent\b'     = 'PhanTramTienTrinh'
    '\bIsStreaking\b'         = 'DangChuoi'
    '\bIsLastChance\b'        = 'CoHoiCuoi'
    '\bIsCorrect\b'           = 'LaDung'
    '\bFilledLetters\b'       = 'ChuCaiDaDien'
    '\bSlotIndex\b'           = 'ViTriO'
    '\bQuestionText\b'        = 'CauHoi'
    '\bCurrentIndex\b'        = 'ViTriHienTai'
    '\bGrade\b'               = 'XepLoai'
    '\bAccuracy\b'            = 'DoChinhXac'
    '\bMode\b'                = 'CheDo'
    # ── Game Methods (BUS) ─────────────────────────────────────────
    '\bInitializeGameAsync\b' = 'KhoiTaoGameAsync'
    '\bAddLetter\b'           = 'ThemChuCai'
    '\bRemoveLettersFrom\b'   = 'XoaChuCaiTu'
    '\bUseHint\b'             = 'DungGoiY'
    '\bStartGame\b'           = 'BatDauGame'
    '\bStopGame\b'            = 'DungGame'
    '\bCheckAnswer\b'         = 'KiemTraDapAn'
    '\bLoadCurrentWord\b'     = 'TaiTuHienTai'
    '\bStartLogicTimer\b'     = 'BatDauHenGio'
    '\bStopLogicTimer\b'      = 'DungHenGio'
    '\bGetWordsForLevel\b'    = 'LayTuChoMuc'
    '\bGetGameRule\b'         = 'LayLuatChoi'
    '\bSaveGameResultAsync\b' = 'LuuKetQuaGameAsync'
    '\bRemoveLetterFromAvailable\b' = 'XoaChuCaiKhaDung'
    '\bReturnLetterToAvailable\b'   = 'TraChuCaiVeKhaDung'
    '\bGetCurrentState\b'     = 'LayTrangThaiHienTai'
    '\bGetCurrentQuestion\b'  = 'LayCauHoiHienTai'
    # ── Word Methods (BUS/DAL) ─────────────────────────────────────
    '\bGetWordsByTopic\b'          = 'LayTuTheoChuDe'
    '\bGetWordsByTopicAndDifficulty\b' = 'LayTuTheoChuDeVaDoKho'
    '\bGetWordsByLevelID\b'        = 'LayTuTheoMaMuc'
    '\bSearchWords\b'              = 'TimKiemTu'
    '\bAddWord\b'                  = 'ThemTuMoi'
    '\bIsDuplicateEnglishWord\b'   = 'LaTuTiengAnhTrung'
    '\bIsWordInUse\b'              = 'TuDangDuocDung'
    '\bGetWords\b'                 = 'LayTu'
    # ── Enum ───────────────────────────────────────────────────────
    '\bAnswerResult\b'        = 'KetQuaTraLoi'
    '\bAnswerResult\.Invalid\b' = 'KetQuaTraLoi.KhongHopLe'
    '\bAnswerResult\.Full\b'    = 'KetQuaTraLoi.DayO'
    '\bAnswerResult\.Added\b'   = 'KetQuaTraLoi.DaThem'
    '\bAnswerResult\.Correct\b' = 'KetQuaTraLoi.Dung'
    '\bAnswerResult\.Wrong\b'   = 'KetQuaTraLoi.Sai'
    # ── Game Result Properties ─────────────────────────────────────
    '\bTimeTaken\b'           = 'ThoiGianDaChoi'
    '\bScore\b'               = 'Diem'
    '\bStars\b'               = 'SoSao'
    '\bTotalScore\b'          = 'TongDiem'
    '\bTotalStars\b'          = 'TongSao'
}

$files = Get-ChildItem -Path '.' -Recurse -Filter *.cs
foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
    $original = $content
    foreach ($key in $replacements.Keys) {
        $content = [regex]::Replace($content, $key, $replacements[$key])
    }
    if ($content -cne $original) {
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8
        Write-Host "Updated: $($file.Name)"
    }
}
Write-Host "`nHoàn thành Việt hoá toàn bộ identifier còn lại!"
